package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
@Entity
@Table(name="ADMINISTRATOR"
    ,schema="WAPLJ"
)
public class Administrator  implements java.io.Serializable {


     private String brukernavn;

    public Administrator() {
    }

    public Administrator(String brukernavn) {
       this.brukernavn = brukernavn;
    }
   
     @Id 
    
    @Column(name="BRUKERNAVN", unique=true, nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }




}


