package Modell;
// Generated 03.apr.2013 13:17:58 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bruker generated by hbm2java
 */
@Entity
@Table(name="bruker"
    ,catalog="waplj"
)
public class Bruker  implements java.io.Serializable {


     private String brukernavn;
     private String passord;
     private String fornavn;
     private String etternavn;
     private String adresse;
     private String email;
     private int telefon;
     private Integer postnummer;

    public Bruker() {
    }

	
    public Bruker(String brukernavn, String passord, String fornavn, String etternavn, String adresse, String email, int telefon) {
        this.brukernavn = brukernavn;
        this.passord = passord;
        this.fornavn = fornavn;
        this.etternavn = etternavn;
        this.adresse = adresse;
        this.email = email;
        this.telefon = telefon;
    }
    public Bruker(String brukernavn, String passord, String fornavn, String etternavn, String adresse, String email, int telefon, Integer postnummer) {
       this.brukernavn = brukernavn;
       this.passord = passord;
       this.fornavn = fornavn;
       this.etternavn = etternavn;
       this.adresse = adresse;
       this.email = email;
       this.telefon = telefon;
       this.postnummer = postnummer;
    }
   
     @Id 
    
    @Column(name="brukernavn", unique=true, nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    
    @Column(name="passord", nullable=false, length=10)
    public String getPassord() {
        return this.passord;
    }
    
    public void setPassord(String passord) {
        this.passord = passord;
    }
    
    @Column(name="fornavn", nullable=false, length=10)
    public String getFornavn() {
        return this.fornavn;
    }
    
    public void setFornavn(String fornavn) {
        this.fornavn = fornavn;
    }
    
    @Column(name="etternavn", nullable=false, length=10)
    public String getEtternavn() {
        return this.etternavn;
    }
    
    public void setEtternavn(String etternavn) {
        this.etternavn = etternavn;
    }
    
    @Column(name="adresse", nullable=false, length=20)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
    @Column(name="email", nullable=false, length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="telefon", nullable=false)
    public int getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(int telefon) {
        this.telefon = telefon;
    }
    
    @Column(name="postnummer")
    public Integer getPostnummer() {
        return this.postnummer;
    }
    
    public void setPostnummer(Integer postnummer) {
        this.postnummer = postnummer;
    }




}


