package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kunde generated by hbm2java
 */
@Entity
@Table(name="KUNDE"
    ,schema="WAPLJ"
)
public class Kunde  implements java.io.Serializable {


     private String brukernavn;
     private Integer avslag;

    public Kunde() {
    }

	
    public Kunde(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    public Kunde(String brukernavn, Integer avslag) {
       this.brukernavn = brukernavn;
       this.avslag = avslag;
    }
   
     @Id 
    
    @Column(name="BRUKERNAVN", unique=true, nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    
    @Column(name="AVSLAG")
    public Integer getAvslag() {
        return this.avslag;
    }
    
    public void setAvslag(Integer avslag) {
        this.avslag = avslag;
    }




}


