package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ordre generated by hbm2java
 */
@Entity
@Table(name="ORDRE"
    ,schema="WAPLJ"
)
public class Ordre  implements java.io.Serializable {


     private OrdreId id;
     private Date datoendret;
     private Date datolevert;
     private Date bekreftet;
     private String betaltstatus;
     private Integer selskapnr;

    public Ordre() {
    }

	
    public Ordre(OrdreId id) {
        this.id = id;
    }
    public Ordre(OrdreId id, Date datoendret, Date datolevert, Date bekreftet, String betaltstatus, Integer selskapnr) {
       this.id = id;
       this.datoendret = datoendret;
       this.datolevert = datolevert;
       this.bekreftet = bekreftet;
       this.betaltstatus = betaltstatus;
       this.selskapnr = selskapnr;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="brukernavn", column=@Column(name="BRUKERNAVN", nullable=false, length=10) ), 
        @AttributeOverride(name="salgsnummer", column=@Column(name="SALGSNUMMER", nullable=false, length=10) ) } )
    public OrdreId getId() {
        return this.id;
    }
    
    public void setId(OrdreId id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATOENDRET", length=10)
    public Date getDatoendret() {
        return this.datoendret;
    }
    
    public void setDatoendret(Date datoendret) {
        this.datoendret = datoendret;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATOLEVERT", length=10)
    public Date getDatolevert() {
        return this.datolevert;
    }
    
    public void setDatolevert(Date datolevert) {
        this.datolevert = datolevert;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="BEKREFTET", length=10)
    public Date getBekreftet() {
        return this.bekreftet;
    }
    
    public void setBekreftet(Date bekreftet) {
        this.bekreftet = bekreftet;
    }
    
    @Column(name="BETALTSTATUS", length=10)
    public String getBetaltstatus() {
        return this.betaltstatus;
    }
    
    public void setBetaltstatus(String betaltstatus) {
        this.betaltstatus = betaltstatus;
    }
    
    @Column(name="SELSKAPNR")
    public Integer getSelskapnr() {
        return this.selskapnr;
    }
    
    public void setSelskapnr(Integer selskapnr) {
        this.selskapnr = selskapnr;
    }




}


