package Modell;
// Generated 03.apr.2013 14:31:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ordre generated by hbm2java
 */
@Entity
@Table(name="ordre"
    ,catalog="waplj"
)
public class Ordre  implements java.io.Serializable {


     private OrdreId id;
     private Date datoEndret;
     private Date datoLevert;
     private Date bekreftet;
     private String betaltstatus;
     private Integer selskapnr;

    public Ordre() {
    }

	
    public Ordre(OrdreId id) {
        this.id = id;
    }
    public Ordre(OrdreId id, Date datoEndret, Date datoLevert, Date bekreftet, String betaltstatus, Integer selskapnr) {
       this.id = id;
       this.datoEndret = datoEndret;
       this.datoLevert = datoLevert;
       this.bekreftet = bekreftet;
       this.betaltstatus = betaltstatus;
       this.selskapnr = selskapnr;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="brukernavn", column=@Column(name="brukernavn", nullable=false, length=10) ), 
        @AttributeOverride(name="salgsnummer", column=@Column(name="salgsnummer", nullable=false, length=10) ) } )
    public OrdreId getId() {
        return this.id;
    }
    
    public void setId(OrdreId id) {
        this.id = id;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="datoEndret", length=10)
    public Date getDatoEndret() {
        return this.datoEndret;
    }
    
    public void setDatoEndret(Date datoEndret) {
        this.datoEndret = datoEndret;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="datoLevert", length=10)
    public Date getDatoLevert() {
        return this.datoLevert;
    }
    
    public void setDatoLevert(Date datoLevert) {
        this.datoLevert = datoLevert;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="bekreftet", length=10)
    public Date getBekreftet() {
        return this.bekreftet;
    }
    
    public void setBekreftet(Date bekreftet) {
        this.bekreftet = bekreftet;
    }
    
    @Column(name="betaltstatus", length=10)
    public String getBetaltstatus() {
        return this.betaltstatus;
    }
    
    public void setBetaltstatus(String betaltstatus) {
        this.betaltstatus = betaltstatus;
    }
    
    @Column(name="selskapnr")
    public Integer getSelskapnr() {
        return this.selskapnr;
    }
    
    public void setSelskapnr(Integer selskapnr) {
        this.selskapnr = selskapnr;
    }




}


