package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ordretabell generated by hbm2java
 */
@Entity
@Table(name="ORDRETABELL"
    ,schema="WAPLJ"
)
public class Ordretabell  implements java.io.Serializable {


     private OrdretabellId id;
     private String rettnummer;

    public Ordretabell() {
    }

    public Ordretabell(OrdretabellId id, String rettnummer) {
       this.id = id;
       this.rettnummer = rettnummer;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="salgsnummer", column=@Column(name="SALGSNUMMER", nullable=false, length=10) ), 
        @AttributeOverride(name="selgerbrukernavn", column=@Column(name="SELGERBRUKERNAVN", nullable=false, length=10) ), 
        @AttributeOverride(name="kundebrukernavn", column=@Column(name="KUNDEBRUKERNAVN", nullable=false, length=10) ) } )
    public OrdretabellId getId() {
        return this.id;
    }
    
    public void setId(OrdretabellId id) {
        this.id = id;
    }
    
    @Column(name="RETTNUMMER", nullable=false, length=10)
    public String getRettnummer() {
        return this.rettnummer;
    }
    
    public void setRettnummer(String rettnummer) {
        this.rettnummer = rettnummer;
    }




}


