package Modell;
// Generated 03.apr.2013 14:31:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Retter generated by hbm2java
 */
@Entity
@Table(name="retter"
    ,catalog="waplj"
)
public class Retter  implements java.io.Serializable {


     private String rettnummer;
     private String navn;
     private String beskrivelse;
     private String ingredienser;
     private Integer kalorier;
     private Integer vekt;
     private Integer pris;

    public Retter() {
    }

	
    public Retter(String rettnummer, String navn) {
        this.rettnummer = rettnummer;
        this.navn = navn;
    }
    public Retter(String rettnummer, String navn, String beskrivelse, String ingredienser, Integer kalorier, Integer vekt, Integer pris) {
       this.rettnummer = rettnummer;
       this.navn = navn;
       this.beskrivelse = beskrivelse;
       this.ingredienser = ingredienser;
       this.kalorier = kalorier;
       this.vekt = vekt;
       this.pris = pris;
    }
   
     @Id 
    
    @Column(name="rettnummer", unique=true, nullable=false, length=10)
    public String getRettnummer() {
        return this.rettnummer;
    }
    
    public void setRettnummer(String rettnummer) {
        this.rettnummer = rettnummer;
    }
    
    @Column(name="navn", nullable=false, length=10)
    public String getNavn() {
        return this.navn;
    }
    
    public void setNavn(String navn) {
        this.navn = navn;
    }
    
    @Column(name="beskrivelse", length=30)
    public String getBeskrivelse() {
        return this.beskrivelse;
    }
    
    public void setBeskrivelse(String beskrivelse) {
        this.beskrivelse = beskrivelse;
    }
    
    @Column(name="ingredienser", length=30)
    public String getIngredienser() {
        return this.ingredienser;
    }
    
    public void setIngredienser(String ingredienser) {
        this.ingredienser = ingredienser;
    }
    
    @Column(name="kalorier")
    public Integer getKalorier() {
        return this.kalorier;
    }
    
    public void setKalorier(Integer kalorier) {
        this.kalorier = kalorier;
    }
    
    @Column(name="vekt")
    public Integer getVekt() {
        return this.vekt;
    }
    
    public void setVekt(Integer vekt) {
        this.vekt = vekt;
    }
    
    @Column(name="pris")
    public Integer getPris() {
        return this.pris;
    }
    
    public void setPris(Integer pris) {
        this.pris = pris;
    }




}


