package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Rolle generated by hbm2java
 */
@Entity
@Table(name="ROLLE"
    ,schema="WAPLJ"
)
public class Rolle  implements java.io.Serializable {


     private String brukernavn;
     private String rollen;

    public Rolle() {
    }
    
    public Rolle(String brukernavn) {
        this.brukernavn = brukernavn;
    }

    public Rolle(String brukernavn, String rollen) {
       this.brukernavn = brukernavn;
       this.rollen = rollen;
    }
   

    @Column(name="BRUKERNAVN", nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }

    @Column(name="ROLLEN", nullable=false, length=10)
    public String getRollen() {
        return this.rollen;
    }
    
    public void setRollen(String rollen) {
        this.rollen = rollen;
    }


  
   
   


}


