package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Salg generated by hbm2java
 */
@Entity
@Table(name="SALG"
    ,schema="WAPLJ"
)
public class Salg  implements java.io.Serializable {


     private String salgsnummer;
     private String sumsalg;

    public Salg() {
    }

	
    public Salg(String salgsnummer) {
        this.salgsnummer = salgsnummer;
    }
    public Salg(String salgsnummer, String sumsalg) {
       this.salgsnummer = salgsnummer;
       this.sumsalg = sumsalg;
    }
   
     @Id 
    
    @Column(name="SALGSNUMMER", unique=true, nullable=false, length=10)
    public String getSalgsnummer() {
        return this.salgsnummer;
    }
    
    public void setSalgsnummer(String salgsnummer) {
        this.salgsnummer = salgsnummer;
    }
    
    @Column(name="SUMSALG", length=10)
    public String getSumsalg() {
        return this.sumsalg;
    }
    
    public void setSumsalg(String sumsalg) {
        this.sumsalg = sumsalg;
    }




}


