package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Selgere generated by hbm2java
 */
@Entity
@Table(name="SELGERE"
    ,schema="WAPLJ"
)
public class Selgere  implements java.io.Serializable {


     private String brukernavn;
     private String salgpermaned;
     private String opparbeidetprovisjon;
     private String antsalg;
     private String timer;

    public Selgere() {
    }

	
    public Selgere(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    public Selgere(String brukernavn, String salgpermaned, String opparbeidetprovisjon, String antsalg, String timer) {
       this.brukernavn = brukernavn;
       this.salgpermaned = salgpermaned;
       this.opparbeidetprovisjon = opparbeidetprovisjon;
       this.antsalg = antsalg;
       this.timer = timer;
    }
   
     @Id 
    
    @Column(name="BRUKERNAVN", unique=true, nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    
    @Column(name="SALGPERMANED", length=10)
    public String getSalgpermaned() {
        return this.salgpermaned;
    }
    
    public void setSalgpermaned(String salgpermaned) {
        this.salgpermaned = salgpermaned;
    }
    
    @Column(name="OPPARBEIDETPROVISJON", length=10)
    public String getOpparbeidetprovisjon() {
        return this.opparbeidetprovisjon;
    }
    
    public void setOpparbeidetprovisjon(String opparbeidetprovisjon) {
        this.opparbeidetprovisjon = opparbeidetprovisjon;
    }
    
    @Column(name="ANTSALG", length=10)
    public String getAntsalg() {
        return this.antsalg;
    }
    
    public void setAntsalg(String antsalg) {
        this.antsalg = antsalg;
    }
    
    @Column(name="TIMER", length=10)
    public String getTimer() {
        return this.timer;
    }
    
    public void setTimer(String timer) {
        this.timer = timer;
    }




}


