package Modell;
// Generated 03.apr.2013 14:31:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Selskaper generated by hbm2java
 */
@Entity
@Table(name="selskaper"
    ,catalog="waplj"
)
public class Selskaper  implements java.io.Serializable {


     private Integer selskapnr;
     private Integer avslag;
     private Integer akkumulertSalg;

    public Selskaper() {
    }

    public Selskaper(Integer avslag, Integer akkumulertSalg) {
       this.avslag = avslag;
       this.akkumulertSalg = akkumulertSalg;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="selskapnr", unique=true, nullable=false)
    public Integer getSelskapnr() {
        return this.selskapnr;
    }
    
    public void setSelskapnr(Integer selskapnr) {
        this.selskapnr = selskapnr;
    }
    
    @Column(name="avslag")
    public Integer getAvslag() {
        return this.avslag;
    }
    
    public void setAvslag(Integer avslag) {
        this.avslag = avslag;
    }
    
    @Column(name="akkumulertSalg")
    public Integer getAkkumulertSalg() {
        return this.akkumulertSalg;
    }
    
    public void setAkkumulertSalg(Integer akkumulertSalg) {
        this.akkumulertSalg = akkumulertSalg;
    }




}


