package Modell;
// Generated 03.apr.2013 14:31:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SelskapKunde generated by hbm2java
 */
@Entity
@Table(name="selskapKunde"
    ,catalog="waplj"
)
public class SelskapKunde  implements java.io.Serializable {


     private SelskapKundeId id;

    public SelskapKunde() {
    }

    public SelskapKunde(SelskapKundeId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="brukernavn", column=@Column(name="brukernavn", nullable=false, length=10) ), 
        @AttributeOverride(name="selskapnr", column=@Column(name="selskapnr", nullable=false) ) } )
    public SelskapKundeId getId() {
        return this.id;
    }
    
    public void setId(SelskapKundeId id) {
        this.id = id;
    }




}


