package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Selskapkunde generated by hbm2java
 */
@Entity
@Table(name="SELSKAPKUNDE"
    ,schema="WAPLJ"
)
public class Selskapkunde  implements java.io.Serializable {


     private SelskapkundeId id;

    public Selskapkunde() {
    }

    public Selskapkunde(SelskapkundeId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="brukernavn", column=@Column(name="BRUKERNAVN", nullable=false, length=10) ), 
        @AttributeOverride(name="selskapnr", column=@Column(name="SELSKAPNR", nullable=false) ) } )
    public SelskapkundeId getId() {
        return this.id;
    }
    
    public void setId(SelskapkundeId id) {
        this.id = id;
    }




}


