package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Selskaper generated by hbm2java
 */
@Entity
@Table(name="SELSKAPER"
    ,schema="WAPLJ"
)
public class Selskaper  implements java.io.Serializable {


     private int selskapnr;
     private Integer avslag;
     private Integer akkumulertsalg;

    public Selskaper() {
    }

	
    public Selskaper(int selskapnr) {
        this.selskapnr = selskapnr;
    }
    public Selskaper(int selskapnr, Integer avslag, Integer akkumulertsalg) {
       this.selskapnr = selskapnr;
       this.avslag = avslag;
       this.akkumulertsalg = akkumulertsalg;
    }
   
     @Id 
    
    @Column(name="SELSKAPNR", unique=true, nullable=false)
    public int getSelskapnr() {
        return this.selskapnr;
    }
    
    public void setSelskapnr(int selskapnr) {
        this.selskapnr = selskapnr;
    }
    
    @Column(name="AVSLAG")
    public Integer getAvslag() {
        return this.avslag;
    }
    
    public void setAvslag(Integer avslag) {
        this.avslag = avslag;
    }
    
    @Column(name="AKKUMULERTSALG")
    public Integer getAkkumulertsalg() {
        return this.akkumulertsalg;
    }
    
    public void setAkkumulertsalg(Integer akkumulertsalg) {
        this.akkumulertsalg = akkumulertsalg;
    }




}


