package Modell;
// Generated 03.apr.2013 14:31:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sjoforer generated by hbm2java
 */
@Entity
@Table(name="sjoforer"
    ,catalog="waplj"
)
public class Sjoforer  implements java.io.Serializable {


     private String brukernavn;
     private String forekortklasse;

    public Sjoforer() {
    }

    public Sjoforer(String brukernavn, String forekortklasse) {
       this.brukernavn = brukernavn;
       this.forekortklasse = forekortklasse;
    }
   
     @Id 
    
    @Column(name="brukernavn", unique=true, nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    
    @Column(name="Forekortklasse", nullable=false, length=10)
    public String getForekortklasse() {
        return this.forekortklasse;
    }
    
    public void setForekortklasse(String forekortklasse) {
        this.forekortklasse = forekortklasse;
    }




}


