package Modell;
// Generated 03.apr.2013 13:17:58 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtkjoringId generated by hbm2java
 */
@Embeddable
public class UtkjoringId  implements java.io.Serializable {


     private String brukernavn;
     private String salgsnummer;
     private int bilnr;
     private String sjoforBrukernavn;

    public UtkjoringId() {
    }

    public UtkjoringId(String brukernavn, String salgsnummer, int bilnr, String sjoforBrukernavn) {
       this.brukernavn = brukernavn;
       this.salgsnummer = salgsnummer;
       this.bilnr = bilnr;
       this.sjoforBrukernavn = sjoforBrukernavn;
    }
   

    @Column(name="brukernavn", nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }

    @Column(name="salgsnummer", nullable=false, length=10)
    public String getSalgsnummer() {
        return this.salgsnummer;
    }
    
    public void setSalgsnummer(String salgsnummer) {
        this.salgsnummer = salgsnummer;
    }

    @Column(name="bilnr", nullable=false)
    public int getBilnr() {
        return this.bilnr;
    }
    
    public void setBilnr(int bilnr) {
        this.bilnr = bilnr;
    }

    @Column(name="sjoforBrukernavn", nullable=false, length=10)
    public String getSjoforBrukernavn() {
        return this.sjoforBrukernavn;
    }
    
    public void setSjoforBrukernavn(String sjoforBrukernavn) {
        this.sjoforBrukernavn = sjoforBrukernavn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtkjoringId) ) return false;
		 UtkjoringId castOther = ( UtkjoringId ) other; 
         
		 return ( (this.getBrukernavn()==castOther.getBrukernavn()) || ( this.getBrukernavn()!=null && castOther.getBrukernavn()!=null && this.getBrukernavn().equals(castOther.getBrukernavn()) ) )
 && ( (this.getSalgsnummer()==castOther.getSalgsnummer()) || ( this.getSalgsnummer()!=null && castOther.getSalgsnummer()!=null && this.getSalgsnummer().equals(castOther.getSalgsnummer()) ) )
 && (this.getBilnr()==castOther.getBilnr())
 && ( (this.getSjoforBrukernavn()==castOther.getSjoforBrukernavn()) || ( this.getSjoforBrukernavn()!=null && castOther.getSjoforBrukernavn()!=null && this.getSjoforBrukernavn().equals(castOther.getSjoforBrukernavn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBrukernavn() == null ? 0 : this.getBrukernavn().hashCode() );
         result = 37 * result + ( getSalgsnummer() == null ? 0 : this.getSalgsnummer().hashCode() );
         result = 37 * result + this.getBilnr();
         result = 37 * result + ( getSjoforBrukernavn() == null ? 0 : this.getSjoforBrukernavn().hashCode() );
         return result;
   }   


}


