package Modell;
// Generated 03.apr.2013 14:31:55 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Utkjoring generated by hbm2java
 */
@Entity
@Table(name="utkjoring"
    ,catalog="waplj"
)
public class Utkjoring  implements java.io.Serializable {


     private UtkjoringId id;
     private String utkorinKogstatus;

    public Utkjoring() {
    }

	
    public Utkjoring(UtkjoringId id) {
        this.id = id;
    }
    public Utkjoring(UtkjoringId id, String utkorinKogstatus) {
       this.id = id;
       this.utkorinKogstatus = utkorinKogstatus;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="brukernavn", column=@Column(name="brukernavn", nullable=false, length=10) ), 
        @AttributeOverride(name="salgsnummer", column=@Column(name="salgsnummer", nullable=false, length=10) ), 
        @AttributeOverride(name="bilnr", column=@Column(name="bilnr", nullable=false) ), 
        @AttributeOverride(name="sjoforBrukernavn", column=@Column(name="sjoforBrukernavn", nullable=false, length=10) ) } )
    public UtkjoringId getId() {
        return this.id;
    }
    
    public void setId(UtkjoringId id) {
        this.id = id;
    }
    
    @Column(name="utkorinKogstatus", length=10)
    public String getUtkorinKogstatus() {
        return this.utkorinKogstatus;
    }
    
    public void setUtkorinKogstatus(String utkorinKogstatus) {
        this.utkorinKogstatus = utkorinKogstatus;
    }




}


