package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utkjoringsbil generated by hbm2java
 */
@Entity
@Table(name="UTKJORINGSBIL"
    ,schema="WAPLJ"
)
public class Utkjoringsbil  implements java.io.Serializable {


     private int bilnr;
     private String regnummer;
     private String status;

    public Utkjoringsbil() {
    }

    public Utkjoringsbil(int bilnr, String regnummer, String status) {
       this.bilnr = bilnr;
       this.regnummer = regnummer;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="BILNR", unique=true, nullable=false)
    public int getBilnr() {
        return this.bilnr;
    }
    
    public void setBilnr(int bilnr) {
        this.bilnr = bilnr;
    }
    
    @Column(name="REGNUMMER", nullable=false, length=10)
    public String getRegnummer() {
        return this.regnummer;
    }
    
    public void setRegnummer(String regnummer) {
        this.regnummer = regnummer;
    }
    
    @Column(name="STATUS", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


