package Modell;
// Generated 13.mar.2013 20:07:38 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UtkjoringId generated by hbm2java
 */
@Embeddable
public class UtkjoringId  implements java.io.Serializable {


     private String brukernavn;
     private String salgsnummer;
     private int bilnr;
     private String sjoforbrukernavn;

    public UtkjoringId() {
    }

    public UtkjoringId(String brukernavn, String salgsnummer, int bilnr, String sjoforbrukernavn) {
       this.brukernavn = brukernavn;
       this.salgsnummer = salgsnummer;
       this.bilnr = bilnr;
       this.sjoforbrukernavn = sjoforbrukernavn;
    }
   

    @Column(name="BRUKERNAVN", nullable=false, length=10)
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }

    @Column(name="SALGSNUMMER", nullable=false, length=10)
    public String getSalgsnummer() {
        return this.salgsnummer;
    }
    
    public void setSalgsnummer(String salgsnummer) {
        this.salgsnummer = salgsnummer;
    }

    @Column(name="BILNR", nullable=false)
    public int getBilnr() {
        return this.bilnr;
    }
    
    public void setBilnr(int bilnr) {
        this.bilnr = bilnr;
    }

    @Column(name="SJOFORBRUKERNAVN", nullable=false, length=10)
    public String getSjoforbrukernavn() {
        return this.sjoforbrukernavn;
    }
    
    public void setSjoforbrukernavn(String sjoforbrukernavn) {
        this.sjoforbrukernavn = sjoforbrukernavn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UtkjoringId) ) return false;
		 UtkjoringId castOther = ( UtkjoringId ) other; 
         
		 return ( (this.getBrukernavn()==castOther.getBrukernavn()) || ( this.getBrukernavn()!=null && castOther.getBrukernavn()!=null && this.getBrukernavn().equals(castOther.getBrukernavn()) ) )
 && ( (this.getSalgsnummer()==castOther.getSalgsnummer()) || ( this.getSalgsnummer()!=null && castOther.getSalgsnummer()!=null && this.getSalgsnummer().equals(castOther.getSalgsnummer()) ) )
 && (this.getBilnr()==castOther.getBilnr())
 && ( (this.getSjoforbrukernavn()==castOther.getSjoforbrukernavn()) || ( this.getSjoforbrukernavn()!=null && castOther.getSjoforbrukernavn()!=null && this.getSjoforbrukernavn().equals(castOther.getSjoforbrukernavn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBrukernavn() == null ? 0 : this.getBrukernavn().hashCode() );
         result = 37 * result + ( getSalgsnummer() == null ? 0 : this.getSalgsnummer().hashCode() );
         result = 37 * result + this.getBilnr();
         result = 37 * result + ( getSjoforbrukernavn() == null ? 0 : this.getSjoforbrukernavn().hashCode() );
         return result;
   }   


}


